name: e_grocery
description: "Personal Finance Tracker App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  fl_chart: ^0.66.1  # ✅ Updated to latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  path: ^1.8.3
